name: Deploy to Heroku

on:
  push:
    branches:
      - herokuu

jobs:
   deploy:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Set up Node.js
           uses: actions/setup-node@v2
           with:
              node-version: 18

         - name: Install Backend Dependencies
           run: cd backend && yarn install

         - name: Lint Backend
           run: cd backend && yarn lint

         - name: Install Frontend Dependencies
           run: cd frontend && yarn install

         - name: Build Frontend
           run: cd frontend && yarn build

         - name: Copy Build to Backend Public Folder
           run: cp -r frontend/build/* backend/public/
           
         - name: Install Heroku CLI
           run: |
              curl https://cli-assets.heroku.com/install.sh | sh

         - name: Set Heroku Config
           run: |
              echo "machine api.heroku.com login $HEROKU_EMAIL password $HEROKU_API_KEY" >> ~/.netrc
              chmod 600 ~/.netrc

         - name: Deploy to Heroku
           run: |
              heroku pipelines:promote -a staffshipcc-development-bot

         - name: Deploy to Heroku
           run: |
              git remote add heroku https://git.heroku.com/staffshipcc-development-bot.git
              git push heroku herokuu:staffshipcc-development-bot

         - name: Restart Heroku App
           run: |
              heroku restart -a staffshipcc-development-bot
           env:
              HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
              HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
