name: Pull Request Checks

on:
  pull_request:
    branches:
      - dev

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Backend Dependencies
        run: cd backend && yarn install

      - name: Lint Backend
        run: cd backend && yarn lint

      - name: Install Frontend Dependencies
        run: cd frontend && yarn install

      - name: Build Frontend
        run: cd frontend && yarn build

      - name: Copy Build to Backend Public Folder
        run: cp -r frontend/build/* backend/public/

  pr_verified:
    name: Pull request verified
    needs: [lint_and_test]
    runs-on: ubuntu-latest
    steps:
      - name: Successful pr
        run: echo Successful pr